package com.habitdev.sprout.enums;

public enum HomeConfigurationKeys {

    HOME_SHAREDPREF("HOME_SHARED.PREF"),
    HOME_ADD_DEFAULT_SHAREDPREF("HOME_ADD_DEFAULT_SHARED.PREF"),
    HOME_HABIT_ON_MODIFY_SHARED_PREF("HOME_HABIT_ON_MODIFY_SHARED.PREF"),

    IS_ON_ADD_DEFAULT("ON_ADD_DEAFAULT.BOOL"),
    IS_ON_ADD_NEW("ON_ADD_NEW.BOOL"),
    IS_ON_ITEM_CLICK("ON_ITEM_CLICK"),
    IS_ON_MODIFY("ON_MODIFY.BOOL"),

    SELECTED_COLOR("SELECTED_COLOR.INT"),
    OLD_SELECTED_COLOR("OLD_SELECTED_COLOR.INT"),
    SELECTED_HABIT("SELECTED_HABIT.STRING"),
    SUBROUTINE("SUBROUTINE.SUBROUTINES"),
    LIST_SIZE("LIST.INT"),
    HABIT("TITLE.HABIT"),
    TITLE("TITLE.STRING"),
    DESCRIPTION("DESCRIPTION.STRING"),
    POSITION("POSITION.INT"),
    HINT_TEXT("HINT.STRING");

    private final String value;

    HomeConfigurationKeys(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
